version: 2

updates:
  # Main
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo

  # Docker
  - package-ecosystem: docker
    directory: "/images/golangci_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/images/hadolint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/images/shellcheck"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  # Java
  - package-ecosystem: gradle
    directory: "/images/checkstyle"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/images/pmd_cpd"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/images/pmd_java"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  # Java (Kotlin)
  - package-ecosystem: gradle
    directory: "/images/detekt"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/images/ktlint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  # JavaScript
  # TODO: CoffeeLint's package name seems moved. See https://github.com/sider/runners/issues/821
  - package-ecosystem: npm
    directory: "/images/eslint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/images/jshint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/images/remark_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/images/stylelint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/images/tyscan"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # PHP
  - package-ecosystem: composer
    directory: "/images/code_sniffer"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: composer
    directory: "/images/phinder"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: composer
    directory: "/images/phpmd"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # Python
  - package-ecosystem: pip
    directory: "/images/cpplint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/images/metrics_complexity"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/images/flake8"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/images/pylint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  # Ruby
  - package-ecosystem: bundler
    directory: "/images/brakeman"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/goodcheck"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/haml_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/querly"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/rails_best_practices"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/reek"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/rubocop"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/images/scss_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
