require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-rubycw

inherit_gem:
  meowcop:
    - config/rubocop.yml

Style/MutableConstant:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "test/**/*_test.rb"
