AllCops:
  NewCops: enable

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-rubycw

inherit_gem:
  meowcop:
    - config/rubocop.yml

Style/MutableConstant:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "test/**/*_test.rb"

# TODO: https://github.com/rubocop-hq/rubocop/issues/8718
Lint/EmptyFile:
  Enabled: false
