sudo: false
cache: bundler
language: ruby
services:
  - docker
env:
  - ANALYZER=none
  - ANALYZER=rubocop
  - ANALYZER=reek
  - ANALYZER=goodcheck
  - ANALYZER=code_sniffer
before_install:
  - gem install bundler
  - nvm install
  - npm install -g yarn
branches:
  only:
    - master

script:
  - export TAG="${TRAVIS_TAG:-${TRAVIS_COMMIT}}"
  - if [ "$ANALYZER" = 'none' ]; then bundle exec rake test; fi
  # TODO: Enable typecheck after migrating to this repository
  # - bundle exec rake typecheck
  - if [ "$ANALYZER" = 'none' ]; then bundle exec rake dockerfile:generate; fi
  - if [ "$ANALYZER" = 'none' ]; then bundle exec rake dockerfile:verify; fi
  - if [ "$ANALYZER" != 'none' ]; then bundle exec rake docker:build; fi
  - if [ "$ANALYZER" != 'none' ]; then bundle exec rake docker:smoke; fi
