name: Bump analyzers

on:
  schedule:
    - cron: "0 0 1,5,15,25 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
      - run: |
          gem install bundler --no-document
          bundle config set path vendor/bundle
          bundle install --jobs=4 --retry=3
      - run: |
          bundle exec rake bump:analyzers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_AUTHOR_NAME: GitHub Actions
          GITHUB_AUTHOR_EMAIL: actions@github.com
